version: 2
jobs:
  build:
    docker:
      - image: trzeci/emscripten:sdk-incoming-64bit
    steps:
      - run:
          name: Clone repo and build dependencies
          command: |
            git clone --recursive https://github.com/k2snowman69/threadily-sample
      - run:
          name: Checkout branch
          command: |
            cd ./threadily-sample/threadily 
            git fetch --all
            git checkout ${CIRCLE_BRANCH}
      - run:
          name: Build threadily-sample and run test
          command: make test
