version: 2
jobs:
  build:
    docker:
      - image: trzeci/emscripten:sdk-incoming-64bit
    steps:
      - run: git clone https://github.com/k2snowman69/shared-makefile
      - run: git clone https://github.com/k2snowman69/threadily
      - run: cd threadily
      - run: make
