version: 2
jobs:
  build:
    docker:
      - image: trzeci/emscripten:sdk-incoming-64bit
    steps:
      - run:
          name: Clone repo and build dependencies
          command: |
            git clone https://github.com/k2snowman69/shared-makefile
            git clone https://github.com/k2snowman69/threadily
            git clone https://github.com/k2snowman69/threadily-sample-cpp
            git clone https://github.com/k2snowman69/threadily-sample-cpp-test
      - run:
          name: Checkout branch
          command: |
            cd threadily 
            git fetch --all
            git checkout ${CIRCLE_BRANCH}
      - run:
          name: Make threadily
          command: |
            cd threadily
            make
      - run:
          name: Make threadily-sample-cpp
          command: |
            cd threadily-sample-cpp
            make
      - run:
          name: Make threadily-sample-cpp-test
          command: |
            cd threadily-sample-cpp-test
            make test
