version: 2
jobs:
  build:
    docker:
      - image: trzeci/emscripten:sdk-incoming-64bit
    steps:
      - run:
          name: Clone shared-makefile
          command: git clone https://github.com/k2snowman69/shared-makefile
      - run:
          name: Clone threadily
          command: git clone https://github.com/k2snowman69/threadily
      - run:
          name: Checkout branch
          command: cd threadily && git fetch --all && git checkout ${CIRCLE_BRANCH}
      - run:
          name: Run make
          command: cd threadily && make
